// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALzr2bHd7edVFSvUHPOIt0yTouH_TdgGA',
    appId: '1:539919741562:web:432851c2dfb9ea6b3801c3',
    messagingSenderId: '539919741562',
    projectId: 'assistant-usco',
    authDomain: 'assistant-usco.firebaseapp.com',
    storageBucket: 'assistant-usco.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOguG4NkEdh-WHf30XLBxYCabxoINS4Yg',
    appId: '1:539919741562:android:d4184909f7e7680e3801c3',
    messagingSenderId: '539919741562',
    projectId: 'assistant-usco',
    storageBucket: 'assistant-usco.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmA6RTlob3HO8AfjjIuy_nhS8uRXw7M3g',
    appId: '1:539919741562:ios:5d806bcd0afa574c3801c3',
    messagingSenderId: '539919741562',
    projectId: 'assistant-usco',
    storageBucket: 'assistant-usco.firebasestorage.app',
    iosBundleId: 'com.example.crochet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmA6RTlob3HO8AfjjIuy_nhS8uRXw7M3g',
    appId: '1:539919741562:ios:5d806bcd0afa574c3801c3',
    messagingSenderId: '539919741562',
    projectId: 'assistant-usco',
    storageBucket: 'assistant-usco.firebasestorage.app',
    iosBundleId: 'com.example.crochet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALzr2bHd7edVFSvUHPOIt0yTouH_TdgGA',
    appId: '1:539919741562:web:0e513913add904ea3801c3',
    messagingSenderId: '539919741562',
    projectId: 'assistant-usco',
    authDomain: 'assistant-usco.firebaseapp.com',
    storageBucket: 'assistant-usco.firebasestorage.app',
  );
}
